<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\review.application\review.application.csproj" />
    <ProjectReference Include="..\review.Persistence\review.Persistence.csproj" />
  </ItemGroup>

</Project>
