syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "result.proto";

package WardGrpcCommand;

service WardCommand {
  rpc CreateWard(CreateWardRequest) returns (CommonResult);
  rpc UpdateWard(UpdateWardRequest) returns (CommonResult);
  rpc DeleteWard(DeleteWardRequest) returns (CommonResult);
}

message CreateWardRequest {
  optional google.protobuf.StringValue Name = 1;
  optional google.protobuf.StringValue NameEn = 2;
  optional google.protobuf.StringValue FullName = 3;
  optional google.protobuf.StringValue FullNameEn = 4;
  optional google.protobuf.DoubleValue Latitude = 5;
  optional google.protobuf.DoubleValue Longitude = 6;
  optional google.protobuf.Int32Value DistrictId = 7;
}

message UpdateWardRequest {
  optional google.protobuf.Int32Value Id = 1;
  optional google.protobuf.StringValue Name = 2;
  optional google.protobuf.StringValue NameEn = 3;
  optional google.protobuf.StringValue FullName = 4;
  optional google.protobuf.StringValue FullNameEn = 5;
  optional google.protobuf.DoubleValue Latitude = 6;
  optional google.protobuf.DoubleValue Longitude = 7;
  optional google.protobuf.Int32Value DistrictId = 8;
}

message DeleteWardRequest {
  optional google.protobuf.Int32Value Id = 1;
}
