<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_365EJSC.ERP.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\365ejsc.erp.Application\365EJSC.ERP.Application.csproj" />
    <ProjectReference Include="..\365ejsc.erp.Persistence\365EJSC.ERP.Persistence.csproj" />
  </ItemGroup>

</Project>
